-- migrate:up
CREATE TABLE tasks (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(20) NOT NULL,
  description VARCHAR(100),
  completed BOOLEAN,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL
);

-- migrate:down

